import React from 'react';
import { motion } from 'framer-motion';
import { Leaf, Globe, Recycle, AlertTriangle } from 'lucide-react';
import Hero from '../components/Hero';

const About = () => {
  return (
    <div className="min-h-screen">
      <title>Understanding Waste Management - Environmental Education India</title>
      
      <Hero
        title="Understanding Waste Management Fundamentals"
        subtitle="Comprehensive education about waste lifecycle, environmental impact, and sustainable solutions for India's growing waste challenges."
        backgroundImage="https://images.pexels.com/photos/1006293/pexels-photo-1006293.jpeg"
      />

      {/* What is Waste Management Section */}
      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="text-center mb-16"
          >
            <Leaf className="h-16 w-16 mx-auto mb-6 text-green-600" />
            <h2 className="text-3xl md:text-4xl font-bold text-slate-800 mb-6">What is Waste Management?</h2>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.2 }}
            className="max-w-4xl mx-auto"
          >
            <div className="bg-green-50 rounded-lg p-8 shadow-lg">
              <p className="text-lg text-slate-700 leading-relaxed mb-6">
                Waste management encompasses collection, transportation, processing, recycling, and disposal of waste 
                materials generated by human activities. Effective systems protect public health, environmental quality, 
                and conserve natural resources through systematic approaches. The process begins with waste generation 
                and continues through segregation, collection, treatment, and final disposal or recovery.
              </p>
              <p className="text-lg text-slate-700 leading-relaxed">
                Modern waste management emphasizes waste hierarchy principles: reduce, reuse, recycle, recover, and dispose. 
                Integrated systems combine multiple technologies and strategies for optimal resource recovery and environmental 
                protection. Successful programs require collaboration between government agencies, private sector, and community 
                participation. Proper management reduces greenhouse gas emissions, prevents soil and water contamination, 
                and supports circular economy development.
              </p>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Environmental Impact Section */}
      <section className="py-20 bg-red-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="text-center mb-16"
          >
            <AlertTriangle className="h-16 w-16 mx-auto mb-6 text-red-600" />
            <h2 className="text-3xl md:text-4xl font-bold text-slate-800 mb-6">Environmental Impact</h2>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.2 }}
            className="max-w-4xl mx-auto"
          >
            <div className="bg-white rounded-lg p-8 shadow-lg">
              <p className="text-lg text-slate-700 leading-relaxed mb-6">
                Improper waste management creates severe environmental consequences affecting air, water, and soil quality. 
                Landfills produce methane gas, contributing to climate change and global warming. Plastic pollution harms 
                marine ecosystems, affecting wildlife and food chains dramatically. Toxic chemicals from electronic waste 
                contaminate groundwater supplies permanently.
              </p>
              <p className="text-lg text-slate-700 leading-relaxed">
                Open burning releases harmful pollutants causing respiratory problems and air quality deterioration. 
                Organic waste in landfills produces leachate, contaminating soil and nearby water bodies. Microplastics 
                enter food systems through water and agricultural contamination. Poor waste practices contribute to urban 
                flooding by blocking drainage systems completely.
              </p>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Global Perspective Section */}
      <section className="py-20 bg-blue-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="text-center mb-16"
          >
            <Globe className="h-16 w-16 mx-auto mb-6 text-blue-600" />
            <h2 className="text-3xl md:text-4xl font-bold text-slate-800 mb-6">Global Perspective</h2>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.2 }}
            className="max-w-4xl mx-auto"
          >
            <div className="bg-white rounded-lg p-8 shadow-lg">
              <p className="text-lg text-slate-700 leading-relaxed mb-6">
                Countries worldwide face similar waste management challenges requiring innovative solutions and international 
                cooperation. Denmark leads in waste-to-energy technology, converting 80% of waste into electricity and heating. 
                Japan emphasizes source reduction and has achieved 20% waste reduction through strict regulations. Germany's 
                dual system successfully manages 67% recycling rates through producer responsibility programs.
              </p>
              <p className="text-lg text-slate-700 leading-relaxed">
                Sweden imports waste from neighboring countries to fuel energy production facilities. Developing nations 
                focus on informal recycling sectors and community-based programs. International agreements promote technology 
                transfer and capacity building for sustainable waste management systems globally.
              </p>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Benefits Section */}
      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="text-center mb-16"
          >
            <Recycle className="h-16 w-16 mx-auto mb-6 text-green-600" />
            <h2 className="text-3xl md:text-4xl font-bold text-slate-800 mb-6">Benefits of Proper Management</h2>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {[
              {
                title: 'Environmental Protection',
                description: 'Reduces pollution, conserves natural resources, and protects ecosystems from contamination.'
              },
              {
                title: 'Public Health',
                description: 'Prevents disease spread, reduces air pollution, and ensures clean water supplies.'
              },
              {
                title: 'Economic Benefits',
                description: 'Creates jobs, reduces disposal costs, and generates revenue from recycled materials.'
              },
              {
                title: 'Climate Action',
                description: 'Reduces greenhouse gas emissions and supports climate change mitigation efforts.'
              },
              {
                title: 'Resource Recovery',
                description: 'Recovers valuable materials and energy from waste streams through circular economy principles.'
              },
              {
                title: 'Community Development',
                description: 'Improves quality of life, supports local businesses, and builds environmental awareness.'
              }
            ].map((benefit, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: index * 0.1 }}
                className="bg-green-50 rounded-lg p-6 shadow-lg hover:shadow-xl transition-all duration-300"
              >
                <h3 className="text-lg font-bold text-green-800 mb-3">{benefit.title}</h3>
                <p className="text-slate-700 leading-relaxed">{benefit.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

    </div>
  );
};

export default About;